package pjw.produclistitem.sql;

public class SQL {
	public static final String PRODUCTLIST_SELECT_NEW = 
			"SELECT PID, PNAME, PIMG_URL, CNAME " + 
			"FROM (SELECT PID, PNAME, PIMG_URL, PDATE, CID FROM S_PRODUCT WHERE PDATE>=add_months( PDATE, -1) ORDER BY PDATE DESC) P " + 
			"INNER JOIN S_P_CATE C ON P.CID=C.CID";
	public static final String PRODUCTLIST_SELECT_POP = 
			"SELECT P.PID, P.PNAME, P.PIMG_URL, C.CNAME FROM " + 
			"    (SELECT SUM(dp_quantity) QUAN,PID FROM S_D_PRODUCT GROUP BY PID) PRANK " + 
			"    INNER JOIN S_PRODUCT P ON PRANK.PID=P.PID " + 
			"    INNER JOIN S_P_CATE C ON P.CID=C.CID ORDER BY QUAN DESC";
	public static final String PRODUCTLIST_SELECT_CATE =
			"SELECT P.PID, P.PNAME, P.PIMG_URL, C.CNAME " + 
			"FROM S_PRODUCT P INNER JOIN S_P_CATE C " + 
			"ON P.CID=C.CID WHERE P.CID=? ORDER BY PDATE DESC";
	
	public static final String PRODUCTLIST_SELECT_KEYWORD =
			"SELECT P.PID, P.PNAME, P.PIMG_URL, C.CNAME " + 
			"FROM S_PRODUCT P INNER JOIN S_P_CATE C " + 
			"ON P.CID=C.CID WHERE PNAME LIKE ? ORDER BY PDATE DESC";
}
