package pjw.produclistitem.sql;

public class SQL {
	public static final String PRODUCTLIST_SELECT_NEW = 
			"SELECT P.PID, P.PNAME, P.PIMG_URL, C.CNAME, P.PPRICE, P.QUAN, P.PDATE FROM " + 
			"(SELECT P.PID, P.PNAME, P.PIMG_URL, P.PPRICE, P.CID, P.PPOST_YN, P.PDATE, NVL(QUAN,0) QUAN " + 
			"FROM S_PRODUCT P  " + 
			"LEFT JOIN (SELECT SUM(dp_quantity) QUAN,PID FROM S_D_PRODUCT GROUP BY PID) PRANK " + 
			"ON PRANK.PID=P.PID WHERE P.PPOST_YN='Y') P " + 
			"INNER JOIN S_P_CATE C ON P.CID=C.CID ORDER BY P.PDATE DESC";
	
	public static final String PRODUCTLIST_SELECT_POP = 
			"SELECT P.PID, P.PNAME, P.PIMG_URL, C.CNAME, P.PPRICE, P.QUAN, P.PDATE FROM " + 
					"(SELECT P.PID, P.PNAME, P.PIMG_URL, P.PPRICE, P.CID, P.PPOST_YN, P.PDATE, NVL(QUAN,0) QUAN " + 
					"FROM S_PRODUCT P  " + 
					"LEFT JOIN (SELECT SUM(dp_quantity) QUAN,PID FROM S_D_PRODUCT GROUP BY PID) PRANK " + 
					"ON PRANK.PID=P.PID WHERE P.PPOST_YN='Y') P " + 
					"INNER JOIN S_P_CATE C ON P.CID=C.CID ORDER BY P.QUAN DESC";
	
	public static final String PRODUCTLIST_SELECT_CATE =
			"SELECT P.PID, P.PNAME, P.PIMG_URL, C.CNAME, P.PPRICE " + 
			"FROM S_PRODUCT P INNER JOIN S_P_CATE C " + 
			"ON P.CID=C.CID WHERE P.PPOST_YN='Y' AND P.CID=? ORDER BY PDATE DESC";
	
	public static final String PRODUCTLIST_SELECT_KEYWORD =
			"SELECT P.PID, P.PNAME, P.PIMG_URL, C.CNAME, P.PPRICE " + 
			"FROM S_PRODUCT P INNER JOIN S_P_CATE C " + 
			"ON P.CID=C.CID WHERE PNAME LIKE ? AND P.PPOST_YN='Y' ORDER BY PDATE DESC";
}
